# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@0.12.0

jobs:
  k8s-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUB_OCTETO_CONFIG
      - run:
          command: sed -i -e "s/CREDENTIAL_ENV/${CREDENTIAL_ENV}/g" ./k8s/deploy.yml
          name: replace in the creds env file content
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-name: deployment/blog-backend
          namespace: blog-backend-kinshukmajee
          resource-file-path: ./k8s/deploy.yml
          watch-timeout: "5m"
      - run:
          command: kubectl rollout restart deployment/blog-backend -n blog-backend-kinshukmajee
          name: restart rollout

workflows:
  build-and-deploy-into-k8s:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/kin-blog-backend
          tag: latest
      - k8s-deploy:
          requires:
            - docker/publish
